import type React from "react"
import type { LightbulbIcon as LucideProps } from "lucide-react"
import {
  Mail,
  User,
  Settings,
  Home,
  Calendar,
  FileText,
  Folder,
  ImageIcon,
  Camera,
  Video,
  Music,
  Heart,
  Star,
  Bookmark,
  Bell,
  MessageSquare,
  Phone,
  Search,
  Lock,
  Key,
  Cloud,
  Download,
  Upload,
  Trash,
  Edit,
  Eye,
  Globe,
  Map,
  BarChart,
  LineChart,
  DollarSign,
  CreditCard,
  Gift,
  Tag,
  Link,
  Share,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Sun,
  Moon,
} from "lucide-react"

interface IconComponentProps extends LucideProps {
  type: string
}

export function IconComponent({ type, ...props }: IconComponentProps) {
  const iconMap: Record<string, React.ComponentType<LucideProps>> = {
    mail: Mail,
    user: User,
    settings: Settings,
    home: Home,
    calendar: Calendar,
    file: FileText,
    folder: Folder,
    image: ImageIcon,
    camera: Camera,
    video: Video,
    music: Music,
    heart: Heart,
    star: Star,
    bookmark: Bookmark,
    bell: Bell,
    message: MessageSquare,
    phone: Phone,
    search: Search,
    lock: Lock,
    key: Key,
    cloud: Cloud,
    download: Download,
    upload: Upload,
    trash: Trash,
    edit: Edit,
    eye: Eye,
    globe: Globe,
    map: Map,
    chart: BarChart,
    graph: LineChart,
    dollar: DollarSign,
    "credit-card": CreditCard,
    gift: Gift,
    tag: Tag,
    link: Link,
    share: Share,
    wifi: Wifi,
    bluetooth: Bluetooth,
    battery: Battery,
    power: Power,
    sun: Sun,
    moon: Moon,
  }

  const IconToRender = iconMap[type] || Mail

  return <IconToRender {...props} />
}
